# Substitua somente os blocos antigos de /test por estes.

location = /test {
    return 302 /test/gb;
}

location = /test/adm {
    proxy_pass http://127.0.0.1:6969;
    include proxy_params;
}

location ^~ /test/adm/ {
    proxy_pass http://127.0.0.1:6969;
    include proxy_params;
}

location = /test/api {
    return 308 /test/api/;
}

location ^~ /test/api/ {
    rewrite ^/test/api/(.*)$ /$1 break;
    proxy_pass http://127.0.0.1:6969;
    include proxy_params;
    proxy_read_timeout 3600s;
    proxy_buffering off;
}

location = /test/ {
    return 302 /test/gb;
}

location ^~ /test/ {
    proxy_pass http://127.0.0.1:6868;
    include proxy_params;
    proxy_read_timeout 3600s;
    proxy_buffering off;
}
